server:
  port: 8081


spring:
  cloud:
    sentinel:
      transport:
        dashboard: localhost:8080
      eager: true
    discovery:
      enabled: true
    zookeeper:
      connect-string: 192.168.0.105:2181
      discovery:
        enabled: true
        root: /services
        instance-host: ${spring.cloud.client.ip-address}
  application:
    name: user-service