server:
  port: 8082

spring:
  cloud:
    discovery:
      enabled: true
    zookeeper:
      connect-string: 192.168.0.111:32643
      discovery:
        enabled: true
        root: /services
        instance-host:  ${spring.cloud.client.ip-address}
  application:
    name: order-service
user-service:
  host: user-service.default.svc.zk